---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha2"], "configMap":
      {"name": "my-config-map","key": "my_script.sh", "hookPath": "/usr/bin/onDefineDomain"}}]'
  labels:
    special: vmi-with-sidecar-hook-configmap
  name: vmi-with-sidecar-hook-configmap
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    memory:
      guest: 1024M
    resources: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: occ-quay.apps.sno.oset.amd.com/alan/kubepod/fedora-with-test-tooling-container-disk:2.0.1
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
